[{
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1434",
    "severity": 8,
    "message": "Unexpected keyword or identifier.",
    "source": "ts",
    "startLineNumber": 4,
    "startColumn": 1,
    "endLineNumber": 4,
    "endColumn": 6,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 4,
    "startColumn": 25,
    "endLineNumber": 4,
    "endColumn": 26,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 34,
    "startColumn": 38,
    "endLineNumber": 34,
    "endColumn": 39,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 61,
    "startColumn": 29,
    "endLineNumber": 61,
    "endColumn": 30,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 96,
    "startColumn": 23,
    "endLineNumber": 96,
    "endColumn": 24,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 128,
    "startColumn": 26,
    "endLineNumber": 128,
    "endColumn": 27,
    "modelVersionId": 10,
    "origin": "extHost1"
}, {
    "resource": "/c:/Users/mahiy/OneDrive/Desktop/Wikigame/WikiGameProjectRepo/public/js/game.js",
    "owner": "typescript",
    "code": "1005",
    "severity": 8,
    "message": "';' expected.",
    "source": "ts",
    "startLineNumber": 150,
    "startColumn": 23,
    "endLineNumber": 150,
    "endColumn": 24,
    "modelVersionId": 10,
    "origin": "extHost1"
}]